lvanfretti/version-control-tutorial

Text-files/file-3.txt
I added my name to the list of text file-3. Thanks for the Git tutorial!
=> Adding Sebastian to the list

Text-files/file-3.txt
=> Adding Larissa Breuning to the list

Text-files/file-3.txt
Completed the Tutorial during the ECSE6170! Thanks, this was fun!
=> Adding Kunj to the list

Text-files/file-3.txt
Completed the Tutorial during the TUM-Modelica Course. Thanks, this was fun :)
=> Adding Bernd to the list

Text-files/file-3.txt
Complete the tutorial. Man, it is longgggg. Anyhow, I enjoyed it! Thanks!
=> Adding Hao's name

Text-files/file-3.txt
Completed the Tutorial during the TUM advanced Modelica modelling course.  Fantastico et grazie mille
=> Ann-Kathrin added to the list

Text-files/file-3.txt
Completed the Tutorial during the Modeling and Simulation for Cyber Physical Systems course. Thanks
=> Adding Jae Hoon James Choi to the list

Text-files/file-3.txt
Completed the tutorial during the ECSE-4170! Thank you!
=> Adding Shunyao Xu to the list

Text-files/file-3.txt
Completed the Tutorial during the ECSE 4170 course! Thanks, this was fun!
=> Adding Nathan Mascari to the list

Text-files/file-3.txt
Completed the tutorial during CPS! Thanks, this was fun!
=> Adding Hari Channagiri to the list

Text-files/file-3.txt
Completed the Tutorial during the "Modelica - Git Version Control" course. Thanks, this was fun!
=> Adding G. B. to the list

Text-files/file-3.txt
Completed the Tutorial during the summer! Thanks, this was fun!
=> Adding Davis to the list

Text-files/file-3.txt
Completed the version control tutorial with GitHub. Thanks! I liked it!
=> Adding Miguel Aguilera to the list

Text-files/file-3.txt
Completed the Tutorial during the ECSE-6170! Thanks, this was fun.
=> Adding Junyung Kim to the list

Text-files/file-3.txt
¡Completó el tutorial durante la Tarea de Modelado y Simulación 1B! Gracias esto fue divertido
=> Adding Alberto Alamilla to the list

Text-files/file-3.txt
Accidentally added myself to the S21's list, eventually noticed that after committing.
=> Adding Luechen Wang to the list

Text-files/file-3.txt
Completed the Tutorial during the Mod and Sym for Cyber Physical Systems! Thanks, this was fun!
=> Adding Leia Dziadosz to the list

Text-files/file-3.txt
Completed the Tutorial during the Modeling and Simulation of Cyber-Physical Systems! Thanks, this was fun!
=> Adding Jayson Mintz to the list

Text-files/file-3.txt
Completed the Tutorial during the Modeling and Simulation of CPS course! Thanks, this was fun!
=> Adding Sharmad Joshi to the list

Text-files/file-3.txt
Completed the Tutorial during 2022 RPI ECSE 4170! Thanks.
=> Adding <Cheng Zhang> to the list

Text-files/file-3.txt
Completed the tutorial during Modelling and Simulation of Cyberphysical Systems! Thanks, this was fun!
=> Adding Cole to the list

Text-files/file-3.txt
Completed the Tutorial during the course! Thanks, this was fun!
=> Adding Asad Ullah Amin Shah to the list

Text-files/file-3.txt
=> Adding Aly Noble to the list

Text-files/file-3.txt
Completed the Tutorial during ECSE 4170 Modeling and Simulation for Cyber-Physical Systems! Thanks, this was fun!
=> Adding Wenhao Shen to the list

Text-files/file-3.txt
Completed the Tutorial during the CPS Spring 2022! Thanks, this was fun but also really long and I think I'm losing my mind.
=> Adding Kyle Warns to the list

Text-files/file-3.txt
=> adding hao chang to the list

Text-files/file-3.txt
=> Adding James Onyejizu to the list

Text-files/file-3.txt
Completed the Tutorial during ModSim for CPS in the S22 semester.
=> Adding Eric Segerstrom to the list

Text-files/file-3.txt
Completed tutorial for Modeling CPS S2022
=> Adding Jack Moseley to the list

Text-files/file-3.txt
Added 44- Justin Choi to the bottom of the list of names
=> Adding Justin Choi to the list

Text-files/file-3.txt
Completed the Tutorial during the CPS course Spring 2022! Thanks, this was fun!
=> Adding Brennan Loder to the list

Text-files/file-3.txt
Completed the Tutorial during the Spring '22 ECSE-4170! Thanks, this was fun!
=> Adding Cortez Bartolome to the list

Text-files/file-3.txt
completed the tutorial during mod&sim for CPS class. Nice to actually learn how to GitHub works.
=> Adding Nancy Mathew to the list
